global:
  resolve_timeout: 5m

route:
  receiver: 'sns-notifications'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 30m

receivers:
  - name: 'sns-notifications'
    sns_configs:
      - api_url: https://sns.us-east-1.amazonaws.com
        sigv4:
          region: us-east-1
          
        topic_arn: arn:aws:sns:us-east-1:120569617480:PrometheusAlertsTopic
        send_resolved: true

