apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: otel-demo
  labels:
    app: alertmanager
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9093
      targetPort: 9093
  selector:
    app: alertmanager

